### ISSUE TITLE
Patch for /intgr/gcd.go

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thomaso-mirodin/intmath#1]
```
Fix typo
```

Original issue reported on code.google.com by `giovanni...@gmail.com` on 1 Feb 2015 at 11:53

Attachments:
- [gcd.go.patch](https://storage.googleapis.com/google-code-attachments/intmath/issue-1/comment-0/gcd.go.patch)

**Comment by thomasdesr** [comment]
Resolved
